/* ============================================================
   Datos: 35 sabores reales · 6 reseñas · 6 FAQs · 3 apps
   Categorías: Leche y Crema · Frutales al agua (vegan) · Chocolates · Dulces de Leche
   ============================================================ */

const FLAVORS = [
  // ── LECHE Y CREMA ─────────────────────────────────
  { slug: "pistacho", name: "Pistacho", alt: "Pistacho siciliano",
    cat: "leche-crema", origin: "Sicilia",
    img: "img/flavors/pistacchio.webp",
    sello: { label: "Más pedido", color: "mostaza" },
    desc: "Pistacho siciliano molido en piedra. Cremoso, salado, profundo." },
  { slug: "tiramisu", name: "Tiramisú", alt: "Tiramisú",
    cat: "leche-crema", origin: "Treviso",
    img: "img/flavors/vaso-doble.jpg",
    desc: "Café, mascarpone y bizcocho. La receta de la nonna." },
  { slug: "stracciatella", name: "Stracciatella", alt: "Crema con cacao",
    cat: "leche-crema", origin: "Bérgamo",
    img: "img/flavors/stracciatella.webp",
    sello: { label: "Insignia", color: "cafe" },
    desc: "Crema fior di latte con virutas de chocolate amargo." },
  { slug: "mascarpone-berries", name: "Mascarpone y Berries", alt: "Mascarpone con frutos rojos",
    cat: "leche-crema", origin: "Italia · Sierra",
    img: "img/flavors/mascarpone.jpg",
    desc: "Mascarpone fresco con compota de frutos rojos." },
  { slug: "vainilla-francesa", name: "Vainilla Francesa", alt: "Vainilla bourbon",
    cat: "leche-crema", origin: "Francia",
    img: "img/flavors/brioscia.webp",
    desc: "Vainilla en vaina, infusión lenta." },
  { slug: "cookies-and-cream", name: "Cookies and Cream", alt: "Galleta y crema",
    cat: "leche-crema", origin: "Clásico",
    img: "img/flavors/frappe.jpg",
    desc: "Crema fior di latte con galleta de cacao." },
  { slug: "higos-con-queso", name: "Higos con Queso", alt: "Higo con queso",
    cat: "leche-crema", origin: "Sierra · Italia",
    img: "img/flavors/mandarina-2.jpg",
    sello: { label: "Solo en Roccia", color: "verde" },
    desc: "Confitura casera de higo serrano sobre crema de queso." },
  { slug: "yogurt", name: "Yogurt", alt: "Yogurt griego",
    cat: "leche-crema", origin: "Grecia",
    img: null,
    desc: "Yogurt natural cuajado, ácido y limpio." },
  { slug: "tres-leches", name: "3 Leches", alt: "Torta tres leches",
    cat: "leche-crema", origin: "Latam",
    img: "img/flavors/tulipan.jpg",
    desc: "La torta más querida, hecha helado." },
  { slug: "cheesecake-maracuya", name: "Cheesecake de Maracuyá", alt: "Cheesecake con maracuyá",
    cat: "leche-crema", origin: "Costa · NY",
    img: null,
    desc: "Queso crema con coulis de maracuyá ecuatoriana." },
  { slug: "chicle", name: "Chicle", alt: "Chicle",
    cat: "leche-crema", origin: "Clásico",
    img: null,
    desc: "El sabor de la infancia, en vitrina." },
  { slug: "ron-pasas", name: "Ron Pasas", alt: "Ron con pasas",
    cat: "leche-crema", origin: "Caribe",
    img: null,
    desc: "Pasas maceradas en ron, sobre crema." },
  { slug: "menta-granizada", name: "Menta Granizada", alt: "Menta con cacao",
    cat: "leche-crema", origin: "Andes",
    img: "img/flavors/menta.webp",
    desc: "Menta fresca con virutas de cacao amargo." },
  { slug: "mocca", name: "Mocca", alt: "Café con chocolate",
    cat: "leche-crema", origin: "Manabí · Italia",
    img: "img/flavors/affogato.webp",
    desc: "Café espresso ecuatoriano con cacao." },
  { slug: "banana", name: "Banana", alt: "Banano",
    cat: "leche-crema", origin: "Costa ecuatoriana",
    img: null,
    desc: "Banano maduro de la costa, en crema." },

  // ── FRUTALES AL AGUA · VEGAN ──────────────────────
  { slug: "uva", name: "Uva", alt: "Uva",
    cat: "frutales", vegan: true, origin: "Mendoza",
    img: null,
    desc: "Sorbete de uva, sin lácteo." },
  { slug: "naranjilla", name: "Naranjilla", alt: "Lulo ecuatoriano",
    cat: "frutales", vegan: true, origin: "Andes ecuatorianos",
    img: "img/flavors/naranjilla.webp",
    sello: { label: "Solo en Roccia", color: "verde" },
    desc: "Cítrico tropical de altura. Refresca, persiste." },
  { slug: "mora", name: "Mora", alt: "Mora andina",
    cat: "frutales", vegan: true, origin: "Sierra",
    img: null,
    desc: "Mora de altura, ácida y morada." },
  { slug: "frutilla", name: "Frutilla", alt: "Fresa",
    cat: "frutales", vegan: true, origin: "Sierra ecuatoriana",
    img: "img/flavors/fresa.webp",
    desc: "Frutilla de la sierra, sorbete con trozos." },
  { slug: "taxo", name: "Taxo", alt: "Curuba",
    cat: "frutales", vegan: true, origin: "Andes",
    img: "img/flavors/taxo.webp",
    sello: { label: "Solo en Roccia", color: "verde" },
    desc: "Fruta andina, ácida y aromática." },
  { slug: "guanabana", name: "Guanábana", alt: "Guanábana",
    cat: "frutales", vegan: true, origin: "Costa ecuatoriana",
    img: null,
    desc: "Pulpa fresca de guanábana costeña." },
  { slug: "mandarina", name: "Mandarina", alt: "Mandarina",
    cat: "frutales", vegan: true, origin: "Sierra ecuatoriana",
    img: "img/flavors/mandarina.webp",
    desc: "Mandarina dulce de huerto, sedosa." },
  { slug: "mango", name: "Mango", alt: "Mango ecuatoriano",
    cat: "frutales", vegan: true, origin: "Costa ecuatoriana",
    img: "img/flavors/mango.webp",
    desc: "Mango maduro, pulpa de la costa." },
  { slug: "limon-siciliano", name: "Limón Siciliano", alt: "Limón siciliano",
    cat: "frutales", vegan: true, origin: "Sicilia",
    img: "img/flavors/limon.webp",
    desc: "Limón siciliano. Punzante, limpio, italiano." },
  { slug: "coco", name: "Coco", alt: "Coco",
    cat: "frutales", vegan: true, origin: "Costa",
    img: null,
    desc: "Coco rallado en sorbete cremoso." },
  { slug: "coco-limon", name: "Coco-Limón", alt: "Coco con limón",
    cat: "frutales", vegan: true, origin: "Costa · Sicilia",
    img: null,
    desc: "Coco con punta de limón siciliano." },
  { slug: "uvilla", name: "Uvilla", alt: "Aguaymanto",
    cat: "frutales", vegan: true, origin: "Andes",
    img: null,
    desc: "Uvilla andina, dulce y ácida a la vez." },
  { slug: "maracuya", name: "Maracuyá", alt: "Maracuyá",
    cat: "frutales", vegan: true, origin: "Costa ecuatoriana",
    img: null,
    desc: "Maracuyá entera, semillas incluidas." },
  { slug: "frambuesa", name: "Frambuesa", alt: "Frambuesa",
    cat: "frutales", vegan: true, origin: "Sierra",
    img: null,
    sello: { label: "Nuevo", color: "azul" },
    desc: "Sorbete de frambuesa intenso, recién en vitrina." },

  // ── CHOCOLATES ────────────────────────────────────
  { slug: "chocolate-blanco", name: "Chocolate Blanco", alt: "Chocolate blanco",
    cat: "chocolates", origin: "Italia",
    img: null,
    desc: "Chocolate blanco italiano, dulce equilibrado." },
  { slug: "kinder", name: "Kinder", alt: "Chocolate con leche",
    cat: "chocolates", origin: "Italia",
    img: "img/flavors/kinder.webp",
    desc: "Chocolate con leche al estilo italiano, cremoso." },
  { slug: "choco-avellana", name: "Choco Avellana", alt: "Chocolate con avellana",
    cat: "chocolates", origin: "Piamonte · Manabí",
    img: "img/flavors/choco-avellana.webp",
    desc: "Cacao ecuatoriano con avellana piamontesa tostada." },
  { slug: "chocolate-intenso", name: "Chocolate Intenso", alt: "Chocolate amargo",
    cat: "chocolates", origin: "Manabí",
    img: "img/flavors/torta.webp",
    sello: { label: "Triple origen", color: "cafe" },
    desc: "Cacao 70% de Manabí. Intenso, ligeramente amargo." },

  // ── DULCES DE LECHE ───────────────────────────────
  { slug: "dulce-de-leche", name: "Dulce de Leche", alt: "Dulce de leche clásico",
    cat: "dulces", origin: "Argentina",
    img: "img/flavors/alfajor.jpg",
    sello: { label: "Más pedido", color: "mostaza" },
    desc: "Dulce de leche argentino cocido a fuego lento." },
  { slug: "dulce-de-leche-granizado", name: "Dulce de Leche Granizado", alt: "Dulce de leche con chocolate",
    cat: "dulces", origin: "Argentina",
    img: "img/flavors/pistacho-espatula.jpg",
    desc: "Dulce de leche con virutas de chocolate semiamargo." },
];

const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "leche-crema", label: "Leche y Crema" },
  { id: "frutales", label: "Frutales al agua", vegan: true },
  { id: "chocolates", label: "Chocolates" },
  { id: "dulces", label: "Dulces de Leche" },
];

const TOTAL_FLAVORS = FLAVORS.length;

const REVIEWS = [
  { name: "María José A.", initial: "M", time: "hace 2 semanas", stars: 5,
    text: "El pistacho es de otro nivel. Cremoso, salado, perfecto. Se nota que es el de verdad, no esa pasta verde fluorescente que venden por ahí." },
  { name: "Sebastián V.", initial: "S", time: "hace 1 mes", stars: 5,
    text: "El sorbete de mandarina es de huerto, no de saborizante. Se siente fresco, limpio, vegano. Lo combiné con choco avellana y fue un acierto total." },
  { name: "Daniela P.", initial: "D", time: "hace 3 semanas", stars: 5,
    text: "Mi favorita es la stracciatella. Hace años no comía una así. El ambiente del local en Briza Cumbayá es muy lindo, da ganas de quedarse un rato." },
  { name: "Andrés M.", initial: "A", time: "hace 1 semana", stars: 5,
    text: "El dulce de leche es argentino de verdad. Soy de Buenos Aires y se nota la técnica. Lo pedí por Uber Eats y llegó perfecto, todavía firme." },
  { name: "Camila T.", initial: "C", time: "hace 2 meses", stars: 5,
    text: "El choco avellana me devolvió a Italia. Cremoso, con notas tostadas, nada empalagoso. La atención del local también muy cálida." },
  { name: "Joaquín R.", initial: "J", time: "hace 4 días", stars: 5,
    text: "Volví tres veces en una semana. Sabores diferentes cada vez. La rotación de vitrina es real, no es marketing. Mi pareja se enamoró del cheesecake de maracuyá." },
];

const FAQS = [
  { q: "¿Hacen delivery a domicilio?",
    a: "Sí. Pedís helado Roccia a domicilio por Uber Eats y Rappi. Cubrimos Cumbayá, Tumbaco, Quito y valles cercanos. El tiempo promedio en Cumbayá es de 25 minutos. Llega firme, en envases térmicos. También podés llamarnos directo al local para coordinar pedidos grandes." },
  { q: "¿Dónde están ubicados?",
    a: "Nuestro local está en Briza Cumbayá, Av. Francisco de Orellana, Y y Tajamar. Atendemos todos los días de 10:00 a 20:00. Hay parqueo del centro comercial." },
  { q: "¿Cuántos sabores tienen disponibles?",
    a: "Nuestra carta tiene 35 sabores entre Leche y Crema, Frutales al agua (todos veganos), Chocolates y Dulces de Leche. La vitrina del local cambia con la temporada y los ingredientes que llegan: en general tenés entre 16 y 20 sabores en frío al mismo tiempo. Los frutales de temporada (taxo, naranjilla, guanábana, frambuesa) van rotando." },
  { q: "¿Sus helados son artesanales?",
    a: "Sí, todos. Trabajamos con técnica italiana: pasteurización lenta, maduración mínima de 12 horas, mantecación en lote pequeño. No usamos saborizantes artificiales ni colorantes. Cada lote sale de nuestro laboratorio en Cumbayá. Eso es lo que hace que la textura sea distinta a la del helado industrial." },
  { q: "¿Atienden eventos privados o catering?",
    a: "Sí. Hacemos servicio de carrito de helados para bodas, cumpleaños y eventos corporativos en Quito y valles. También vendemos potes de medio litro y litro para llevar. Para coordinar, escribinos a hola@rocciaheladeria.com con la fecha y el número de invitados." },
  { q: "¿Tienen opciones sin azúcar o veganas?",
    a: "Toda nuestra línea de Frutales al agua (14 sabores) es 100% vegana: solo fruta, agua y azúcar. Para sin azúcar añadida trabajamos por encargo, con 48 horas de aviso, así garantizamos calidad. Consultá en el local por opciones del día." },
];

const DELIVERY_APPS = [
  { name: "Uber Eats", desc: "El más rápido en Cumbayá",
    url: "https://www.ubereats.com" },
  { name: "Rappi", desc: "Delivery con tracking en Quito y valles",
    url: "https://www.rappi.com.ec" },
];

const WHY_REASONS = [
  { icon: "Award", title: "Técnica italiana",
    body: "Laboratorio 100% italiano. Pasteurización lenta, maduración mínima de 12 horas. La textura no se inventa, se construye." },
  { icon: "Leaf", title: "Ingredientes reales",
    body: "Sin saborizantes artificiales ni colorantes. Frutas reales, cacao ecuatoriano, pistacho siciliano molido en piedra." },
  { icon: "Mountain", title: "Origen ecuatoriano",
    body: "Cacao de Manabí y Esmeraldas. Higo de la sierra. Mango y guanábana de la costa. Lo de aquí, hecho aquí." },
  { icon: "Heart", title: "Hecho a mano",
    body: "Cada lote artesanal, controlado. La vitrina cambia con la temporada y los ingredientes que tengamos a mano." },
];

/* ── 8 sabores destacados (cards visibles) ─────────── */
const FEATURED_FLAVORS = [
  { slug: "pistacho", name: "Pistacho", alt: "Helado de pistacho",
    cat: "Cremas", origin: "Italia",
    img: "img/flavors/pistacchio.webp",
    desc: "Pasta de pistacho con grano fino y notas tostadas." },
  { slug: "stracciatella", name: "Stracciatella", alt: "Helado de stracciatella",
    cat: "Cremas", origin: "Italia × Ecuador",
    img: "img/flavors/stracciatella.webp",
    desc: "Crema con láminas de cacao manabita." },
  { slug: "cheesecake-maracuya", name: "Cheesecake de Maracuyá", alt: "Helado de cheesecake con maracuyá",
    cat: "Cremas", origin: "Italia × Ecuador",
    img: "img/flavors/mascarpone.jpg",
    desc: "Crema base cheesecake con maracuyá fresco ecuatoriano." },
  { slug: "mascarpone-berries", name: "Mascarpone y Berries", alt: "Helado de mascarpone con berries",
    cat: "Cremas", origin: "Italia",
    img: "img/flavors/mascarpone-espatula.jpg",
    desc: "Crema de mascarpone con frutos rojos frescos." },
  { slug: "dulce-de-leche", name: "Dulce de Leche", alt: "Helado de dulce de leche",
    cat: "Dulces de Leche", origin: "Argentina",
    img: "img/flavors/alfajor.jpg",
    desc: "Cocción lenta con leche y azúcar a fuego suave." },
  { slug: "choco-avellana", name: "Choco Avellana", alt: "Helado de chocolate con avellana",
    cat: "Chocolates", origin: "Italia",
    img: "img/flavors/choco-avellana.webp",
    desc: "Avellana piamontesa con cacao en notas suaves." },
  { slug: "mandarina", name: "Mandarina", alt: "Sorbete de mandarina",
    cat: "Frutales al Agua", origin: "Ecuador",
    img: "img/flavors/mandarina.webp",
    desc: "Frutal cítrico al agua, fresco y vegano." },
  { slug: "taxo", name: "Taxo", alt: "Sorbete de taxo",
    cat: "Frutales al Agua", origin: "Ecuador",
    img: "img/flavors/taxo.webp",
    desc: "Fruta serrana ecuatoriana, ácido natural balanceado." },
];

/* ── 35 sabores · catálogo completo en 4 columnas (SEO + texto) ── */
const CATALOG_SECTIONS = [
  { id: "leche-crema", title: "Leche y Crema", count: 15, vegan: false,
    items: [
      { name: "Pistacho", slug: "pistacho" },
      { name: "Tiramisú", slug: "tiramisu" },
      { name: "Stracciatella", slug: "stracciatella" },
      { name: "Mascarpone y Berries", slug: "mascarpone-berries" },
      { name: "Vainilla Francesa", slug: "vainilla-francesa" },
      { name: "Cookies and Cream", slug: "cookies-and-cream" },
      { name: "Higos con Queso", slug: "higos-con-queso" },
      { name: "Yogurt", slug: "yogurt" },
      { name: "3 Leches", slug: "tres-leches" },
      { name: "Cheesecake de Maracuyá", slug: "cheesecake-maracuya" },
      { name: "Chicle", slug: "chicle" },
      { name: "Ron Pasas", slug: "ron-pasas" },
      { name: "Menta Granizada", slug: "menta-granizada" },
      { name: "Mocca", slug: "mocca" },
      { name: "Banana", slug: "banana" },
    ]},
  { id: "frutales", title: "Frutales al Agua", count: 14, vegan: true,
    items: [
      { name: "Uva", slug: "uva" },
      { name: "Naranjilla", slug: "naranjilla" },
      { name: "Mora", slug: "mora" },
      { name: "Frutilla", slug: "frutilla" },
      { name: "Taxo", slug: "taxo" },
      { name: "Guanábana", slug: "guanabana" },
      { name: "Mandarina", slug: "mandarina" },
      { name: "Mango", slug: "mango" },
      { name: "Limón Siciliano", slug: "limon-siciliano" },
      { name: "Coco", slug: "coco" },
      { name: "Coco-Limón", slug: "coco-limon" },
      { name: "Uvilla", slug: "uvilla" },
      { name: "Maracuyá", slug: "maracuya" },
      { name: "Frambuesa", slug: "frambuesa" },
    ]},
  { id: "chocolates", title: "Chocolates", count: 4, vegan: false,
    items: [
      { name: "Chocolate Blanco", slug: "chocolate-blanco" },
      { name: "Kinder", slug: "kinder" },
      { name: "Choco Avellana", slug: "choco-avellana" },
      { name: "Chocolate Intenso", slug: "chocolate-intenso" },
    ]},
  { id: "dulces", title: "Dulces de Leche", count: 2, vegan: false,
    items: [
      { name: "Dulce de Leche", slug: "dulce-de-leche" },
      { name: "Dulce de Leche Granizado", slug: "dulce-de-leche-granizado" },
    ]},
];

Object.assign(window, { FLAVORS, CATEGORIES, REVIEWS, FAQS, DELIVERY_APPS, WHY_REASONS, TOTAL_FLAVORS, FEATURED_FLAVORS, CATALOG_SECTIONS });
